import type { MetadataRoute } from "next";

// Web app manifest — this plus a registered service worker (public/sw.js)
// are the two things Chromium checks before it will offer installation.
// Without it `beforeinstallprompt` never fires, so
// src/components/pwa/install-prompt.tsx stays dormant.
//
// Icon PNGs are generated by `node scripts/generate-icons.mjs`. They must
// live at stable paths in public/ (not app/icon.tsx, whose route is
// content-hashed) because the manifest has to name them by URL.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "HopeChat — WhatsApp CRM & Automation",
    short_name: "HopeChat",
    description:
      "Shared inbox, contacts, pipelines, broadcasts, and no-code automations for WhatsApp.",
    // `id` pins the app identity so a future manifest change can't make
    // the browser treat this as a different app and re-prompt installs.
    id: "/dashboard",
    start_url: "/dashboard",
    scope: "/",
    display: "standalone",
    orientation: "portrait-primary",
    background_color: "#ffffff",
    theme_color: "#10b8a2",
    categories: ["business", "productivity", "social"],
    icons: [
      {
        src: "/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
    shortcuts: [
      {
        name: "Inbox",
        short_name: "Inbox",
        url: "/inbox",
        icons: [{ src: "/icon-192.png", sizes: "192x192", type: "image/png" }],
      },
      {
        name: "Broadcasts",
        short_name: "Broadcast",
        url: "/broadcasts",
        icons: [{ src: "/icon-192.png", sizes: "192x192", type: "image/png" }],
      },
      {
        name: "Contacts",
        short_name: "Contacts",
        url: "/contacts",
        icons: [{ src: "/icon-192.png", sizes: "192x192", type: "image/png" }],
      },
    ],
  };
}